[package]
name = "project_blue_rust"
version = "0.1.0"
authors = ["smudgecat123 <jf14218@my.bristol.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
gdnative = "0.9.0"